# Generated by Django 5.0.1 on 2024-01-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.IntegerField(choices=[(1, 'Eskiz'), (2, 'Play Mobile'), (3, 'Get Sms')])),
                ('phone', models.CharField(max_length=13)),
                ('message', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_send', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sms Log',
                'verbose_name_plural': 'Sms Logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SmsSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.IntegerField(choices=[(1, 'Eskiz'), (2, 'Play Mobile'), (3, 'Get Sms')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
